package com.ioactive.aiscanner.vulns;

import java.util.List;

/**
 * A thin vuln-class descriptor. Payloads are generated by the LLM ("engine") at
 * scan time from {@link #guidance}; the only code we maintain is the {@link #oracle}
 * (deterministic detection) and a couple of {@link #fallbackSeeds} used when the LLM
 * is unreachable. This deliberately avoids maintaining a static payload corpus.
 */
public final class VulnClass {

    public enum Severity { HIGH, MEDIUM, LOW, INFORMATION }

    public final String id;              // e.g. "SQL Injection"
    public final String guidance;        // technique hint handed to the LLM
    public final Severity severity;
    public final String remediation;
    public final Oracle oracle;
    public final List<String> fallbackSeeds; // used only if the LLM returns nothing

    public VulnClass(String id, String guidance, Severity severity, String remediation,
                     Oracle oracle, List<String> fallbackSeeds) {
        this.id = id;
        this.guidance = guidance;
        this.severity = severity;
        this.remediation = remediation;
        this.oracle = oracle;
        this.fallbackSeeds = fallbackSeeds;
    }
}
