package com.ioactive.aiscanner.scan;

import burp.api.montoya.MontoyaApi;
import burp.api.montoya.core.Registration;
import burp.api.montoya.http.handler.HttpHandler;
import burp.api.montoya.http.handler.HttpRequestToBeSent;
import burp.api.montoya.http.handler.HttpResponseReceived;
import burp.api.montoya.http.handler.RequestToBeSentAction;
import burp.api.montoya.http.handler.ResponseReceivedAction;
import burp.api.montoya.http.message.requests.HttpRequest;
import burp.api.montoya.http.message.responses.HttpResponse;
import com.ioactive.aiscanner.ui.ScanLog;

import java.net.URI;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.regex.Pattern;

/**
 * WAF-block accounting. Registers ONE Montoya {@link HttpHandler} for the lifetime of a scan and inspects every
 * in-scope response with a block-like status (403/406/429/503).
 *
 * <p><b>Status alone is NOT a WAF.</b> Plenty of apps return 403/406/429/503 from their OWN logic — e.g. Juice
 * Shop's {@code /ftp} route returns {@code 403 "Only .md and .pdf files are allowed!"} from an extension
 * allowlist, not from any WAF. Counting those as "WAF-blocked" (the previous behaviour) produced a bogus "WAF
 * accounting" report on WAF-less sites. So a response is only tallied as WAF-blocked when it carries a REAL WAF
 * signal — a known WAF/CDN fingerprint header, a WAF-ish {@code Server}, or a generic WAF block-page body —
 * NOT merely a block-like status code. App-origin block statuses are counted separately and reported as such.
 *
 * <p>Why an HttpHandler and not per-probe logging: a handler sees ALL traffic Burp processes — our probes AND
 * Burp's own active-audit requests. Observe-only (never mutates traffic). Retains only counters + short URL
 * strings (no HttpRequestResponse), scoped to the target host, bounded — BApp large-project safe.
 */
public final class WafObserver implements HttpHandler {

    private final ScanLog scanLog;
    private final String host;
    private final Registration reg;

    private final AtomicInteger total = new AtomicInteger();      // in-scope responses observed
    private final AtomicInteger statusHits = new AtomicInteger();  // block-like status (any origin)
    private final AtomicInteger wafHits = new AtomicInteger();     // block-like status AND a real WAF signal
    private final AtomicInteger s403 = new AtomicInteger();
    private final AtomicInteger s406 = new AtomicInteger();
    private final AtomicInteger s429 = new AtomicInteger();
    private final AtomicInteger s503 = new AtomicInteger();
    private final Set<String> wafSamples = Collections.synchronizedSet(new LinkedHashSet<>());
    private final Set<String> appSamples = Collections.synchronizedSet(new LinkedHashSet<>());
    private volatile String fingerprint = "";

    // ---- WAF/CDN signals (a block-like status is only "WAF" if one of these matches) ----
    // Presence of any of these response headers ⇒ an edge/WAF handled the response.
    private static final String[] WAF_HEADERS = {
            "cf-ray", "cf-mitigated", "x-amzn-waf-action", "x-sucuri-id", "x-sucuri-block",
            "x-iinfo", "x-datadome", "x-waf", "x-waf-event", "x-waf-action", "x-sq-server"
    };
    // A WAF/CDN identity in the Server header value.
    private static final Pattern WAF_SERVER = Pattern.compile(
            "(?i)(cloudflare|akamaighost|akamai|incapsula|imperva|sucuri|barracuda|fortiweb|"
          + "big-?ip|f5\\b|mod_?security|datadome|wallarm|reblaze|distil|awswaf)");
    // A WAF block-page in the body. Must carry a WAF/firewall-SPECIFIC phrase or a vendor name — NOT a generic
    // security word. Earlier the pattern also matched bare "malicious"/"security reasons"/"access denied"/
    // "reference id", which false-positived on (a) an app that echoes Burp's OWN audit payloads (a reflected
    // <script>alert('malicious')</script> counted as a WAF block!) and (b) normal app copy (an order "reference
    // number"). So a WAF-less target reported phantom WAF blocks. Now: firewall/CRS/WAF-vendor identity only.
    private static final Pattern WAF_BODY = Pattern.compile(
            "(?i)(web application firewall|mod_?security|core rule set|"
          + "request (was |has been )?blocked by|blocked by (our )?(security|firewall|waf|policy)|"
          + "this request (has been|was) (blocked|denied)|attention required!?|ray id|"
          + "generated by wallarm|akamai reference|"
          + "cloudflare|akamaighost|akamai\\b|incapsula|imperva|sucuri|barracuda|fortiweb|"
          + "datadome|awswaf|reblaze|distil networks)");

    /** Registers itself immediately; call {@link #close()} to deregister. */
    public WafObserver(MontoyaApi api, ScanLog scanLog, String host) {
        this.scanLog = scanLog;
        this.host = host == null ? "" : host;
        this.reg = api.http().registerHttpHandler(this);
    }

    @Override
    public RequestToBeSentAction handleHttpRequestToBeSent(HttpRequestToBeSent requestToBeSent) {
        return RequestToBeSentAction.continueWith(requestToBeSent);   // observe only
    }

    @Override
    public ResponseReceivedAction handleHttpResponseReceived(HttpResponseReceived responseReceived) {
        try {
            HttpRequest req = responseReceived.initiatingRequest();
            if (req != null && host.equalsIgnoreCase(hostOf(req.url()))) {
                total.incrementAndGet();
                int st = responseReceived.statusCode();
                if (st == 403 || st == 406 || st == 429 || st == 503) {
                    switch (st) {
                        case 403: s403.incrementAndGet(); break;
                        case 406: s406.incrementAndGet(); break;
                        case 429: s429.incrementAndGet(); break;
                        case 503: s503.incrementAndGet(); break;
                        default: break;
                    }
                    statusHits.incrementAndGet();
                    String sample = req.method() + " " + pathOnly(req.url());
                    String sig = wafSignal(responseReceived);
                    if (sig != null) {                                   // real WAF, not the app
                        wafHits.incrementAndGet();
                        if (wafSamples.size() < 40) wafSamples.add(sample);
                        if (fingerprint.isEmpty()) fingerprint = sig;
                    } else if (appSamples.size() < 20) {                 // app-origin block status
                        appSamples.add(sample);
                    }
                }
            }
        } catch (Throwable ignore) { }
        return ResponseReceivedAction.continueWith(responseReceived);
    }

    /**
     * Returns a short WAF fingerprint string if this block-like response carries a real WAF/CDN signal
     * (fingerprint header, WAF-ish Server, or generic WAF block-page body); {@code null} if it looks
     * app-origin (so a plain app 403/406/429/503 is never miscounted as a WAF block).
     */
    private static String wafSignal(HttpResponse resp) {
        try {
            for (String h : WAF_HEADERS) {
                if (resp.hasHeader(h)) return h + "=" + resp.headerValue(h);
            }
            if (resp.hasHeader("Server")) {
                String sv = resp.headerValue("Server");
                if (sv != null && WAF_SERVER.matcher(sv).find()) return "Server=" + sv;
            }
            String body = resp.bodyToString();
            if (body != null && !body.isEmpty()) {
                if (body.length() > 4096) body = body.substring(0, 4096);
                if (WAF_BODY.matcher(body).find()) return "block-page body signature";
            }
        } catch (Throwable ignore) { }
        return null;
    }

    /** Log the WAF-block summary; call once at scan end (before {@link #close()}). */
    public void summary() {
        int t = total.get();
        if (t == 0) return;
        int waf = wafHits.get();
        int sh = statusHits.get();

        if (waf > 0) {
            scanLog.log("WAF accounting: " + waf + " of " + t + " in-scope response(s) were "
                    + "WAF-BLOCKED (403=" + s403.get() + " 406=" + s406.get() + " 429=" + s429.get()
                    + " 503=" + s503.get() + " by status; " + waf + " with a WAF signal)"
                    + (fingerprint.isEmpty() ? "" : "  [fingerprint: " + fingerprint + "]"));
            synchronized (wafSamples) {
                for (String e : wafSamples) scanLog.log("  WAF-blocked: " + e);
            }
            scanLog.log("NOTE: those responses carried a WAF/edge signal — the WAF, not the app, "
                    + "dropped them. For the full request/response of each (incl. Burp's own audit payloads), "
                    + "see Burp's Logger filtered on status 403/406/429/503. Injection classes blocked here "
                    + "won't appear as findings even if the app is vulnerable (consider WAF-evasion mode); "
                    + "pass-through classes (CSRF/IDOR/access-control/redirect/creds) are unaffected.");
            return;
        }

        // No WAF detected. Say so plainly, and explain any block-like statuses as app-origin.
        if (sh == 0) {
            scanLog.log("WAF accounting: no WAF detected (0 block-like responses of " + t + ").");
            return;
        }
        scanLog.log("WAF accounting: no WAF detected. " + sh + " of " + t + " in-scope response(s) "
                + "returned a block-like status (403=" + s403.get() + " 406=" + s406.get() + " 429=" + s429.get()
                + " 503=" + s503.get() + ") but NONE carried a WAF/edge signal — these are the APP's own "
                + "responses (e.g. an access-control or file-type check), not a WAF block.");
        synchronized (appSamples) {
            for (String e : appSamples) scanLog.log("  app-origin block-status: " + e);
        }
    }

    /** Deregister the handler. Idempotent; call in a finally at scan end. */
    public void close() {
        try { if (reg != null) reg.deregister(); } catch (Throwable ignore) { }
    }

    private static String hostOf(String u) { return Net.authority(u); }
    private static String pathOnly(String u) {
        try { String p = URI.create(u).getPath(); return (p == null || p.isEmpty()) ? u : p; }
        catch (Exception e) { return u; }
    }
}
